api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import StudentViewSet, TrainerViewSet,CourseViewSet,EventViewSet

router = routers.DefaultRouter()
router.register("students",StudentViewSet)
router.register("trainer", TrainerViewSet)
router.register("course", CourseViewSet)
router.register("event", EventViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls))

]

event/urls.py
from django.conf.urls import url
from django.urls import path
from .views import index, CalendarView, event
app_name = 'cal'
urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^cal/$', CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', event, name='event_new'),
	
   
]

school_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls")),
    path("coursecore/", include("coursecore.urls")),
    path("studentcore/", include("studentcore.urls")),
    path("trainercore/", include("trainercore.urls")),
    path('admin/', admin.site.urls),
    path("student/",include("student.urls")),
    path("trainer/", include("trainer.urls")),
    path("course/",include("course.urls")),
    path("event/",include("event.urls")),
    path("api/", include("api.urls")),
  

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

event/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

class Event(models.Model):
    title = models.CharField(max_length=200,null=True,blank=True)
    description = models.TextField(null=True)
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)
    venue=models.CharField(max_length=12,default="AkiraChix")


    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

event/forms.py
from django.forms import ModelForm, DateInput
from django.forms.widgets import TextInput, Textarea
from .models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs=
      {
        'type': 'datetime-local',
        'style': 'max-width: 300px;',
        'class': "form-control",

      }, 
      format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs=
      {
        'type': 'datetime-local',
        'style': 'max-width: 300px;',
        'class': "form-control",
        
      
      },
       
      format='%Y-%m-%dT%H:%M'),

      'title':TextInput(attrs=
      {
        'class': "form-control",
        'style': 'max-width: 300px;',
        'placeholder': 'Event Title'


      }),
      'venue':TextInput(attrs=
      {
        'class': "form-control",
        'style': 'max-width: 300px;',
        'placeholder': 'Event Venue'


      }),
      'description':Textarea(attrs=
      {
        'class': "form-control",
        
        'style': 'max-width: 300px;',
        'placeholder': 'Description'


      })
      
      
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

event/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm

def index(request):
    return HttpResponse('hello')

class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/event.html', {'form': form})

event/templates/cal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  
  <link rel="stylesheet" type="text/css" href="{% static '/static/css/style.css' %}">
  <title>Calender</title>
</head>
<body>
  <style>
      /* Common styles */
body {
  font-family: "ptsans", "Lato", "Helvetica Neue", Helvetica, Arial, sans-serif;
  background-color: antiquewhite;
}
.info {
    border-color: burlywood;
    color:burlywood;
  }
  
  .info:hover {
    background:burlywood;
    color: white;
  }
  .info {
    border-color: burlywood;
    color:burlywood;
  }
  
  .info:hover {
    background:burlywood;
    color: white;
  }
.container {
        margin-top: 10px;
        background-color: white;
        margin-left: 30%;
        width: 500px;
        border:3px solid rgb(252, 205, 143);
        box-shadow: 8px 8px 8px 9px rgb(241, 202, 149);
        border-radius: 10px;

    }
    button{
        background-color: rgb(250, 164, 52);
        color: white;
        border-radius: 10px;
        padding: 10px;
      
        align-items: center;
        width: 300px;
        margin-right: 71px;

    }
    h1  
     {padding-top: 10px;
         color:rgb(230, 156, 59);
        margin-left: 100px;
    }
    p    
    {color: red;}
    form{
        padding-top: 20px;
        padding-left: 80px;
        padding-bottom: 20px;
    }
    .form-group{
        border-color: burlywood;
    }
    #akiralogo{
        width: 80px;
        height:80px;
        padding-bottom: 15px;
        margin-left: 50px;
    }
    hr{
        background-color:burlywood;
        height: 3px;
    }

.left {
  float: left;
}

.right {
  float: right;
}



.clearfix {
  margin: 15px;
}





/* App styles */
.title {
  text-align: center;
  margin: 10px;
}

.calendar {
  width: 98%;
  margin: auto;
  font-size: 13px;
}

.calendar tr, .calendar td {
  border: 1px solid burlywood;
}

.calendar th {
  padding: 10px;
  text-align: center;
  font-size: 18px;
}

.calendar td {
  width: 100px;
  height: 50px;
  padding: 20px 0px 0px 5px;
}

.month {
  font-size: 25px;
}

.date {
  font-size: 16px;
}

ul {
  height: 100%;
  padding: 0px 5px 0px 20px;
}

a {
  color:burlywood;
}
textarea{
  width: 100%;
}
  </style>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  <hr>

  {% block content %}
  {% endblock %}
<!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

event/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}
Calendar
{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn info" href="{% url 'cal:event_new' %}"> Add Event </a>
	
</div>

{{ calendar }}
{% endblock %}

event/templates/cal/edit_calendar.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn info" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!DOCTYPE html>
<html lang="en">

<body>
<style>
    
    
   
    </style>
<div class="container">
<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    <label for="first_name">Event Title:</label>
    <div class="form-group">
        {{ form.title}}
    </div> 
    <label for="second_name">Venue:</label>
    <div class="form-group">
        {{ form.venue}}
    </div>
    <label for="second_name">Description:</label>
    <div class="form-group">
        {{ form.description}}
    </div> 
    <label for="gender">Start_Time:</label>
    <div class="form-group">
        {{ form.start_time}}
    </div>
    <label for="email">End_Time:</label>
    <div class="form-group">
         {{ form.end_time}}
     </div>
    <tr><td colspan="2"><button type="submit" class="register"> Submit </button></td></tr>
  </table>
</form></div>
</body>
</html>
{% endblock %}

event/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn info" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!DOCTYPE html>
<html lang="en">

<body>
<style>
    
    
   
    </style>
<div class="container">
<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    <label for="first_name">Event Title:</label>
    <div class="form-group">
        {{ form.title}}
    </div> 
    <label for="second_name">Venue:</label>
    <div class="form-group">
        {{ form.venue}}
    </div>
    <label for="second_name">Description:</label>
    <div class="form-group">
        {{ form.description}}
    </div> 
    <label for="gender">Start_Time:</label>
    <div class="form-group">
        {{ form.start_time}}
    </div>
    <label for="email">End_Time:</label>
    <div class="form-group">
         {{ form.end_time}}
     </div>
    <tr><td colspan="2"><button type="submit" class="register"> Submit </button></td></tr>
  </table>
</form></div>
</body>
</html>
{% endblock %}