api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import StudentViewSet, TrainerViewSet,CourseViewSet,EventViewSet

router = routers.DefaultRouter()
router.register("students",StudentViewSet)
router.register("trainer", TrainerViewSet)
router.register("course", CourseViewSet)
router.register("event", EventViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls))

]

core/urls.py
from django.urls import path
from .views import home
urlpatterns = [
    path("", home, name="homepage")
]

event/urls.py
from django.conf.urls import url
from django.urls import path
from .views import index, CalendarView, event
app_name = 'cal'
urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^cal/$', CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', event, name='event_new'),
	
   
]

school_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls")),
    path("coursecore/", include("coursecore.urls")),
    path("studentcore/", include("studentcore.urls")),
    path("trainercore/", include("trainercore.urls")),
    path('admin/', admin.site.urls),
    path("student/",include("student.urls")),
    path("trainer/", include("trainer.urls")),
    path("course/",include("course.urls")),
    path("event/",include("event.urls")),
    path("api/", include("api.urls")),
  

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from student.models import Student
from trainer.models import Trainer
from course.models import Course

# Create your views here.

def home(request):
    students = Student.objects.count()
    trainers = Trainer.objects.count()
    courses = Course.objects.count()
    data = {"students":students, 
    "trainers":trainers,
    "courses":courses}
    return render(request, "homepage.html", data)

core/templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .navbar{
            height: 40px;
            border-bottom: 1px solid rgb(165, 207, 214);
           margin-bottom: 2%;
            text-align: center;
            width: 100%;
           
        }
        .navbar:hover{
            box-shadow: 0px 5px 5px 0px rgb(156, 217, 228);
        }
        .navbar a{
            text-decoration: none;
            padding: 20px;
            color: rgb(218, 171, 71);
            font-size: 20px;
           
        }
        #system{
            width: 90%;
            height: 500px;
        }
        .welcome{
            position: absolute;
            top: -3%;
            color:rgb(28, 91, 102) ;
        }
    </style>
</head>
<body>
    <nav class="navbar">
      
        <a href="{%url 'student_page'%}">Students</a>
        <a href="{%url 'trainer_page'%}">Trainers</a>
        <a href="{%url 'course_page'%}">Courses</a>
        <a href="{%url 'cal:calendar'%}">Calendar</a>
        
        
    </nav>
    <div class="welcome">
        <h1>Welcome to the School System</h1>
    </div>
   

    <img id="system" src={% static 'school_system.jpg' %}/>
  

</body>
</html>